In [9]:
import numpy as np
array_example = np.array([[[1, 2], [11, 7]], [[3, 4], [5, 6]]])

print(type(array_example), "\n", "Shape:", array_example.shape, "\n", "Elements:", array_example[0], array_example)

<class 'numpy.ndarray'> 
 Shape: (2, 2, 2) 
 Elements: [[ 1  2]
 [11  7]] [[[ 1  2]
  [11  7]]

 [[ 3  4]
  [ 5  6]]]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [ 9, 10, 11, 12]])
b = a[0:3, 1:3]
print(b)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [11]:
c = a[1:, 2:]
print(c)

[[ 7  8]
 [11 12]]


In [13]:
d = np.ones((2, 3), dtype=np.int32)
print(d)

[[1 1 1]
 [1 1 1]]


In [14]:
e = np.eye(5, dtype=np.int32)
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
