In [3]:
import numpy as np

In [4]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [5]:
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]


In [6]:
preds = np.array([0.2, 0.5, 0.92, 0.9, 0.1])

to_predict_class = ["apple", "banana", "ball", "mango", "orange"]
possible_class_index = np.where(preds > 0.85)[0]
print(possible_class_index)

[2 3]


In [7]:
arr = np.array([1, 4, 7, 2, 8, 4, 9, 10, 10, 8])

print(np.argmax(arr))
print(np.argmin(arr))

7
0


In [8]:
print(np.where(arr >= arr[np.argmax(arr)])[0])

[7 8]


In [9]:
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))

10
1
63


In [12]:
xyz = np.array([[1, 2, 8], [5, 3, 1], [4, 6, 5]])

print(xyz)

print(np.max(xyz, axis=0)) #compute max of each column
print(np.max(xyz, axis=1)) #compute max of each row

[[1 2 8]
 [5 3 1]
 [4 6 5]]
[5 6 8]
[8 5 6]
