In [6]:
import numpy as np

In [7]:
random_number = np.random.rand()
print(random_number)

0.8930465286609971


In [8]:
random_array_1d = np.random.rand(5)
print(random_array_1d)

[0.53015292 0.1846553  0.34437142 0.420992   0.64080087]


In [9]:
random_array_2d = np.random.rand(3, 3)
print(random_array_2d)

[[0.04247805 0.60888611 0.41224705]
 [0.50747026 0.77665754 0.65773208]
 [0.16416604 0.16967692 0.52017992]]


In [10]:
random_int = np.random.randint(0, 10)
print(random_int)

9


In [11]:
random_int_array_2d = np.random.randint(0, 20, size=(3, 2))
print(random_int_array_2d)

[[15  3]
 [13  5]
 [ 8  9]]


In [12]:
random_sample = np.random.choice([1, 2, 3, 4, 5], size=3)
print(random_sample)

[3 4 5]


In [13]:
random_sample_with_replacement = np.random.choice([1, 2, 3, 4, 5], size=3, replace=True)
print(random_sample_with_replacement)

[1 1 5]
